### ISSUE TITLE
method symbols() missing

### ISSUE THREAD

**Issue by webmaster128** [ffflorian/libsodium-type-generator#38]
There is a function 

> `symbols()`: returns a list of the currently methods and constants

in libsodium.js, that is not included in the types at the moment

**Comment by ffflorian** [comment]
Thanks! Fixed in https://github.com/ffflorian/libsodium-type-generator/pull/39 and [v1.2.5](https://github.com/ffflorian/libsodium-type-generator/releases/tag/v2.2.5).

**Comment by webmaster128** [comment]
Wow, that was quick. Thank you for doing this!
