### ISSUE TITLE
Non-sumo

### ISSUE THREAD

**Issue by webmaster128** [ffflorian/libsodium-type-generator#6]
Would it be possible to add  `declare module 'libsodium-wrappers' {` (i.e. the non-sumo version) ?

This would improve the ability to test typings in real-word projects

**Comment by ffflorian** [comment]
@webmaster128
Hi, yes, I am working on that. Unfortunately, `libsodium.js` doesn't describe in the symbol files, which are used in the sumo version.

Until that you can just remove the `-sumo` part. The declaration file will have too many functions then, but it won't give you any syntax errors.

**Comment by webmaster128** [comment]
Oh, I see. Indeed, the wrapper is exactly the same thing not matter if the underlying implementations exist or not. This makes it non trivial.

Just a random idea: if we have a `--base <path>` where `<path>` is a libsodium.js git checkout including submodules, we can read the `EXPORTED_FUNCTIONS_STANDARD` and `EXPORTED_FUNCTIONS_SUMO` from `<base-path>/libsodium/dist-build/emscripten.sh`. However, this does not work with the Github .zip download, which does not include submodules.

**Comment by ffflorian** [comment]
> we can read the EXPORTED_FUNCTIONS_STANDARD and EXPORTED_FUNCTIONS_SUMO from <base-path>/libsodium/dist-build/emscripten.sh

That's exactly my plan but, as you already mentioned, this does not work with the GitHub download.
I could provide the list in the tool, but this would make it much bigger again.

**Comment by webmaster128** [comment]
Hmm duplicating this stuff makes it hard to generate definition files for older versions or other branches of libsodium.js using an up-to-date version of the generator. But given that this tool is only used by a handful of developers and not for the general libsodium.js user, requiring a GIT checkout sounds good.

**Comment by webmaster128** [comment]
Cool, thanks!
